[PKG-3927] humanize 1.1.0 ❄️
AnacondaRecipes/humanize-feedstock pull request #8
Opened 2024-02-20 21:53 UTC by psteyer

humanize 1.1.0 ❄️

Destination channel: Snowflake

## Links
- [PKG3927](https://anaconda.atlassian.net/browse/PKG-3927)
- [upstream repo](https://github.com/python-humanize/humanize/tree/1.1.0)

## Changes
- Updated SHA
- Updated SHA
- added abs.yaml with snowflake channel

2024-02-20 21:54 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_aedmxghrhm/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:41: missing_description: The recipe is missing a description
- clone/recipe/meta.yaml:13: avoid_noarch: noarch: python packages should be avoided

===== ERRORS =====
- clone/recipe/meta.yaml:13: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
===== Final Report: =====
1 Error and 2 Warnings were found

</details>

2024-02-21 15:28 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
Traceback (most recent call last):
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/run.py", line 159, in main
    sys.exit(prime())
             ^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/run.py", line 138, in prime
    result = linter.lint(recipes, subdir, args.variant_config_files, args.exclusive_config_files, args.fix)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/lint/__init__.py", line 735, in lint
    msgs = self.lint_file(
           ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/lint/__init__.py", line 834, in lint_file
    recipe = _recipe.Recipe.from_file(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/recipe.py", line 243, in from_file
    raise exc from exc
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/recipe.py", line 234, in from_file
    recipe._load_from_string(text.read())
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/recipe.py", line 170, in _load_from_string
    self.render()
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/recipe.py", line 290, in render
    self.meta = renderer_utils.render(self.recipe_dir, self.dump(), self.selector_dict, self.renderer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/_renderer.py", line 245, in render
    return ruamel.load(yaml_text.replace("\t", " ").replace("%", " "))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 113, in compose_node
    if self.parser.check_event(AliasEvent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/parser.py", line 146, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/parser.py", line 633, in parse_block_mapping_value
    if not self.scanner.check_token(KeyToken):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/scanner.py", line 1794, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/scanner.py", line 211, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/scanner.py", line 360, in stale_possible_simple_keys
    raise ScannerError(
ruamel.yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 40, column 3:
      This modest package contains var ...
      ^ (line: 40)
could not find expected ':'
  in "<unicode string>", line 41, column 3:
      like turning a number into a fuz ...
      ^ (line: 41)

ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_74z7hkurtx/clone` failed. (See above for error)
</details>

2024-02-21 15:36 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_92aa9toauw/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:23: remove_python_pinning: On arch specific packages, python deps should not be constrained.
- clone/recipe/meta.yaml:21: remove_python_pinning: On arch specific packages, python deps should not be constrained.
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-02-21 15:39 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_0fzb5ympwq/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:21: remove_python_pinning: On arch specific packages, python deps should not be constrained.
- clone/recipe/meta.yaml:23: remove_python_pinning: On arch specific packages, python deps should not be constrained.
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-02-21 18:33 UTC, lorepirri requested changes
@psteyer 
- this must go to `defaults` and not `Snowflake` (remove the `abs.yaml`)
- this package is an older version than what we already have on `defaults` (which is `3.10.0`) and it should be merged into `master-1.1.0` and not `master` following the internal guide https://github.com/anaconda-distribution/perseverance-skills/blob/main/sections/02_Package_building/01_How_tos/Creating_versioned_feedstocks_from_existing_feedstocks.md#create-a-new-submodule
- for more info regarding the destination channel and current versions, please have a look at the ticket [PKG-3927]

Please ping me if you need help with this one :)

2024-02-21 19:33 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_76ft8ipsno/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:21: remove_python_pinning: On arch specific packages, python deps should not be constrained.
- clone/recipe/meta.yaml:23: remove_python_pinning: On arch specific packages, python deps should not be constrained.
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-02-21 20:06 UTC, closed without merging

2024-02-21 20:07 UTC, psteyer commented
Moving the PR to this: https://github.com/AnacondaRecipes/humanize-feedstock/pull/9